const memesData = [
    {
        id: 1,
        title: "#1",
        image: "/images/mem1.jpg",
        upvotes: 12,
        downvotes: 4,
        favorite: false,
    },
    {
      id: 2,
        title: "#2",
        image: "/images/mem2.jpg",
        upvotes: 9,
        downvotes: 4,
        favorite: false,
    },
     {
      id: 3,
        title: "#3",
        image: "/images/mem3.jpg",
        upvotes: 8,
        downvotes: 6,
        favorite: false,
    },
    {
      id: 4,
        title: "#4",
        image: "/images/mem4.jpg",
        upvotes: 18,
        downvotes: 6,
        favorite: false,
    },
    {
      id: 5,
        title: "#5",
        image: "/images/mem5.jpg",
        upvotes: 5,
        downvotes: 1,
        favorite: false,
    },
    {
      id: 6,
        title: "#6",
        image: "/images/mem6.jpg", 
        upvotes: 13,
        downvotes: 8,
        favorite: false,
    },
    {
      id: 7,
        title: "#7",
        image: "/images/mem7.jpg",  
        upvotes: 12,
        downvotes: 8,
        favorite: false,
    },
    {
      id: 8,
        title: "#8",
        image: "/images/mem8.jpg",
        upvotes: 7,
        downvotes: 5,
        favorite: false, 
    },
    {
      id: 9,
        title: "#9",
        image: "/images/mem9.jpg",
        upvotes: 10,
        downvotes: 9,
        favorite: false,
    },
    {
      id: 10,
        title: "#10",
        image: "/images/mem10.jpg",  
        upvotes: 6,
        downvotes: 6,
        favorite: false,
    },
    {
      id: 11,
        title: "#11",
        image: "/images/mem11.jpg", 
        upvotes: 4,
        downvotes: 2,
        favorite: false,
    },
    {
      id: 12,
        title: "#12",
        image: "/images/mem12.jpg",
        upvotes: 7,
        downvotes: 5,
        favorite: false,
    },
    {
      id: 13,
        title: "#13",
        image: "/images/mem13.jpg",  
        upvotes: 2,
        downvotes: 3,
        favorite: false,
    },
    {
      id: 14,
        title: "#14",
        image: "/images/mem14.jpg",  
        upvotes: 5,
        downvotes: 2,
        favorite: false,
    },
    {
      id: 15,
        title: "#15",
        image: "/images/mem15.jpg", 
        upvotes: 12,
        downvotes: 8,
        favorite: false,
    },
    {
      id: 16,
        title: "#16",
        image: "/images/mem16.jpg", 
        upvotes: 15,
        downvotes: 11,
        favorite: false, 
    },
    {
      id: 17,
        title: "#17",
        image: "/images/mem17.jpg",
        upvotes: 11,
        downvotes: 3,
        favorite: false,
    },
    {
      id: 18,
        title: "#18",
        image: "/images/mem18.jpg",  
        upvotes: 12,
        downvotes: 17,
        favorite: false,
    },
    {
      id: 19,
        title: "#19",
        image: "/images/mem19.jpg",  
        upvotes: 11,
        downvotes: 8,
        favorite: false,
    },
     {
      id: 20,
        title: "#20",
        image: "/images/mem20.jpg",  
        upvotes: 16,
        downvotes: 8,
        favorite: false,
    },
     {
      id: 21,
        title: "#21",
        image: "/images/mem21.jpg",  
        upvotes: 3,
        downvotes: 7,
        favorite: false,
    }, {
      id: 22,
        title: "#22",
        image: "/images/mem22.jpg",  
        upvotes: 4,
        downvotes: 8,
        favorite: false,
    },
     {
      id: 23,
        title: "#23",
        image: "/images/mem23.jpg",  
        upvotes: 11,
        downvotes: 7,
        favorite: false,
    },
     {
      id: 24,
        title: "#24",
        image: "/images/mem24.jpg",  
        upvotes: 5,
        downvotes: 2,
        favorite: false,
    },
     {
      id: 25,
        title: "#25",
        image: "/images/mem25.jpg",  
        upvotes: 4,
        downvotes: 2,
        favorite: false,
    },
     {
      id: 26,
        title: "#26",
        image: "/images/mem26.jpg",  
        upvotes: 11,
        downvotes: 5,
        favorite: false,
    },
     {
      id: 27,
        title: "#27",
        image: "/images/mem27.jpg",  
        upvotes: 2,
        downvotes: 12,
        favorite: false,
    },
     {
      id: 28,
        title: "#28",
        image: "/images/mem28.jpg",  
        upvotes: 1,
        downvotes: 8,
        favorite: false,
    },
     {
      id: 29,
        title: "#29",
        image: "/images/mem29.jpg",
        upvotes: 14,
        downvotes: 11,
        favorite: false,
    },
     {
      id: 30,
        title: "#30",
        image: "/images/mem30.jpg",
        upvotes: 11,
        downvotes: 9,
        favorite: false,
    },
   ];

   export default memesData;